"""Tests for the generated comskip.ini (services/comskip_ini.py).

The Comskip settings editor stores tunables in app_settings; at detection
time an INI is generated by overriding those keys in a base INI.  These
tests pin the three load-bearing behaviours:

1. render_comskip_ini replaces existing keys and appends missing ones while
   preserving unrelated lines — especially output_edl=1, which the
   post-processing pipeline requires to find the EDL file.
2. generate_comskip_ini writes the file into the config dir.
3. resolve_comskip_ini precedence: custom INI > generated INI > legacy
   comskip_ini_path fallback when generation fails.
"""
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from models import AppSettings
from services.comskip_ini import (
    GENERATED_INI_NAME,
    generate_comskip_ini,
    render_comskip_ini,
    resolve_comskip_ini,
    tunable_overrides,
)


class RenderComskipIniTests(unittest.TestCase):
    def test_replaces_existing_key_and_drops_inline_comment(self):
        base = "detect_method=255\t\t;1=black frame, 2=logo\noutput_edl=1\n"
        result = render_comskip_ini(base, {"detect_method": 107})
        self.assertIn("detect_method=107", result.splitlines())
        self.assertNotIn("255", result)

    def test_preserves_unrelated_lines(self):
        base = "output_edl=1\nmax_volume=500\t; comment\n"
        result = render_comskip_ini(base, {"detect_method": 107})
        lines = result.splitlines()
        self.assertIn("output_edl=1", lines)
        self.assertIn("max_volume=500\t; comment", lines)

    def test_appends_missing_keys(self):
        base = "output_edl=1\n"
        result = render_comskip_ini(base, {"thread_count": 4, "remove_after": 2})
        lines = result.splitlines()
        self.assertIn("thread_count=4", lines)
        self.assertIn("remove_after=2", lines)
        # output_edl must survive: without it Comskip writes no EDL and
        # commercial removal silently does nothing.
        self.assertIn("output_edl=1", lines)

    def test_commented_out_key_is_not_treated_as_assignment(self):
        base = "; detect_method=99 old note\noutput_edl=1\n"
        result = render_comskip_ini(base, {"detect_method": 107})
        lines = result.splitlines()
        self.assertIn("; detect_method=99 old note", lines)
        self.assertIn("detect_method=107", lines)

    def test_tunable_overrides_reads_model_defaults(self):
        overrides = tunable_overrides(AppSettings(
            comskip_detect_method=107,
            comskip_max_commercialbreak=600,
            comskip_min_commercialbreak=25,
            comskip_max_commercial_size=125,
            comskip_min_commercial_size=4,
            comskip_always_keep_first_seconds=0,
            comskip_always_keep_last_seconds=60,
            comskip_remove_before=0,
            comskip_remove_after=0,
            comskip_thread_count=1,
        ))
        self.assertEqual(overrides, {
            "detect_method": 107,
            "max_commercialbreak": 600,
            "min_commercialbreak": 25,
            "max_commercial_size": 125,
            "min_commercial_size": 4,
            "always_keep_first_seconds": 0,
            "always_keep_last_seconds": 60,
            "remove_before": 0,
            "remove_after": 0,
            "thread_count": 1,
        })

    def test_unset_tunables_are_skipped(self):
        settings = AppSettings()
        settings.comskip_detect_method = None
        settings.comskip_thread_count = 8
        overrides = tunable_overrides(settings)
        self.assertNotIn("detect_method", overrides)
        self.assertEqual(overrides["thread_count"], 8)


class GenerateAndResolveTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.config_dir = Path(self._tmp.name)
        (self.config_dir / "comskip.ini").write_text(
            "detect_method=255\noutput_edl=1\n", encoding="utf-8"
        )
        self.settings = AppSettings(
            comskip_detect_method=107,
            comskip_thread_count=2,
        )

    def tearDown(self):
        self._tmp.cleanup()

    def _patch_config(self):
        return patch(
            "services.comskip_ini.ensure_config_files", return_value=self.config_dir
        )

    def test_generate_writes_overridden_ini(self):
        with self._patch_config():
            path = generate_comskip_ini(self.settings)
        self.assertEqual(path, str(self.config_dir / GENERATED_INI_NAME))
        content = Path(path).read_text(encoding="utf-8")
        self.assertIn("detect_method=107", content.splitlines())
        self.assertIn("thread_count=2", content.splitlines())
        self.assertIn("output_edl=1", content.splitlines())

    def test_generate_falls_back_to_minimal_base_with_edl(self):
        (self.config_dir / "comskip.ini").unlink()
        with self._patch_config(), \
             patch("services.comskip_ini._resolve_bundled_comskip_ini", return_value=None):
            path = generate_comskip_ini(self.settings)
        content = Path(path).read_text(encoding="utf-8")
        self.assertIn("output_edl=1", content.splitlines())
        self.assertIn("detect_method=107", content.splitlines())

    def test_resolve_prefers_custom_ini_and_skips_generation(self):
        self.settings.comskip_custom_ini_path = "/custom/comskip.ini"
        with patch("services.comskip_ini.generate_comskip_ini") as mock_generate:
            result = resolve_comskip_ini(self.settings)
        self.assertEqual(result, "/custom/comskip.ini")
        mock_generate.assert_not_called()

    def test_resolve_blank_custom_uses_generated(self):
        self.settings.comskip_custom_ini_path = "   "
        with self._patch_config():
            result = resolve_comskip_ini(self.settings)
        self.assertEqual(result, str(self.config_dir / GENERATED_INI_NAME))

    def test_resolve_falls_back_to_legacy_path_when_generation_fails(self):
        self.settings.comskip_custom_ini_path = None
        self.settings.comskip_ini_path = "/legacy/comskip.ini"
        with patch("services.comskip_ini.generate_comskip_ini", return_value=None):
            result = resolve_comskip_ini(self.settings)
        self.assertEqual(result, "/legacy/comskip.ini")


if __name__ == "__main__":
    unittest.main()
